# -*- coding: utf-8 -*-
"""
Face Detection.ipynb
Automatically generated by Colaboratory.

"""

!pip install dlib

!pip install face_recognition

!pip3 install opencv-python

import face_recognition
from PIL import Image, ImageDraw

image = face_recognition.load_image_file("IMG-2017.jpg")

face_locations = face_recognition.face_locations(image)

print("I found {} face(s) in this photograph.".format(len(face_locations)))

pil_image = Image.fromarray(image)
# draw = ImageDraw.Draw(pil_image)

import cv2
for face_location in face_locations:
  top, right, bottom, left = face_location
  print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))
  # face_image = image[top:bottom, left:right]
  # pil_image = Image.fromarray(face_image)
  # draw.rectange((left, top, right, bottom), fill=None, outline=(255))
  # pil_image.show()
  rimg = pil_image.copy()
  rimg_draw = ImageDraw.Draw(rimg)
  rimg_draw.rectangle((left, top, right, bottom), fill=None, outline=(0, 255, 0))
  rimg.show()


# pil_image = Image.open("IMG-2017.jpg")
# pil_image
rimg

